### PR TITLE
Update Docker files

### PR DESCRIPTION
**Pull request by mirzamah**
Update Docker files in examples with argument REPO

Change-Id: I7ae1d56003c9b0ce4f6193b807a2e4d2506a0d7a

### CODE REVIEW

**Review by petterwa — COMMENTED** [review]
Looks good. There is one more dockerfile using axisecp:
https://github.com/AxisCommunications/acap3-examples/blob/master/tensorflow-to-larod/env/Dockerfile

**Comment by mirzamah** [comment]
> Looks good. There is one more dockerfile using axisecp:
> https://github.com/AxisCommunications/acap3-examples/blob/master/tensorflow-to-larod/env/Dockerfile

We were supposed to update Dockerfiles for applications that are going to be used for Automated tests that are running only on Camera. Tensorflow is not included.

**Comment by jeanettl** [comment]
Looks good to me

**Review by jeanettl — APPROVED** [review]
Looks good

**Review by kimraxis — APPROVED** [review]

**Pull request merged**
